### PR TITLE
Swift 4.2 support

### PR DESCRIPTION
**Pull request by juliancadi**
- Swift 4.2 & RxSwift 4.3 update.
- New example icon + 1024x1024 res.

### CODE REVIEW

**Review by freak4pc — CHANGES_REQUESTED** [review]
Thanks for your PR. 
All of the changes you've made are not backwards-compatible. Please look at an example of how to properly support both Swift 4 and Swift 4.2, here: 

https://github.com/RxSwiftCommunity/RxKeyboard/pull/73/files

**Comment by juliancadi** [comment]
@freak4pc thanks for the advice! I will look into it and change my PR.

**Comment by juliancadi** [comment]
@freak4pc had you experienced these issues while running CircleCI with Nimble & Carthage before?

**Comment by freak4pc** [comment]
@juliancadi Are the tests running fine locally? Did you also update Quick & Nimble to latest ?

**Comment by juliancadi** [comment]
Yes, they are. I updated Quick (from 1.2.0 to 1.3.2) and Nimble (from 7.0.2 to 7.3.1) as well.

**Comment by freak4pc** [comment]
I think you might've forgotten updating the Xcode version: 
https://github.com/RxSwiftCommunity/RxMKMapView/blob/master/.circleci/config.yml#L10

**Comment by juliancadi** [comment]
I just updated xcode version to the latest one (https://circleci.com/docs/2.0/testing-ios/). It doesn't seem to have any effect on the Quick/Nimble issue.

**Comment by freak4pc** [comment]
It's definitely failing for me locally as well on your branch: 
image

Try running locally and figuring out what's causing the issue: 
`xcodebuild -workspace 'Example/RxMKMapView.xcworkspace' -scheme 'RxMKMapView-Example' -configuration 'Debug' -destination 'platform=iOS Simulator,name=iPhone 8' -sdk iphonesimulator build test | xcpretty -c --test`

**Comment by freak4pc** [comment]
OK, now I'm not sure what's wrong - since its succeeding locally :) Very odd.

**Comment by juliancadi** [comment]
It does run for me locally like a charm:

screen shot 2018-09-23 at 15 56 10

It is very odd indeed ;)

**Comment by juliancadi** [comment]
Should we prepare a TravisCI migration branch? ;)

**Comment by freak4pc** [comment]
Uhm I need to further investigate what’s going on there. Once we find the
issue we can decide on resolution strategy. Will get back to this a bit
later or tomorrow.

Sent from Astro <https://www.astro.ai> for iOS


On Sep 23, 2018 at 17:31, Julian Caicedo <notifications@github.com> wrote:


Should we prepare a TravisCI migration branch? ;)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/RxSwiftCommunity/RxMKMapView/pull/37#issuecomment-423820796>,
or mute the thread

**Comment by diogot** [comment]
Any update about the CI issues?

**Comment by freak4pc** [comment]
I won't have that much time for this soon. Any chance you have some time to further dig into this?

**Comment by diogot** [comment]
Sure, I'll take a look this week.

**Comment by diogot** [comment]
The issue is related to the commited `Pods` directory and the `Carthage` exclusion in `gitignore`.
`Nimble` new version have a directory called `Carthage`, which is not being commited due to the exclusion.
If you change to `Carthage/**` it's possible to commit those files.
I did this fix and other small improvements on CI in #38.

**Comment by juliancadi** [comment]
Solved on https://github.com/RxSwiftCommunity/RxMKMapView/pull/38

**Pull request closed without merging**
