### PR TITLE
2.0.0

### PR DESCRIPTION
**Pull request by thanegill**
### DO NOT MERGE

**This should target a develop branch, will make a new PR when one exists**

---
- Remove mapView prefix from rx_ methods
- Add's `UIControl` to `rx_annotationViewCalloutAccessoryControlTapped`
- Use `castOrThrow` to prevent forced unwrapped optionals
- Use `ControlEvent` on most methods
- Update to RxSwift 2.1.0
- Update to version 2.0.0

### CODE REVIEW

**Comment by thanegill** [comment]
@sger Can you take a look at this?

**Comment by thanegill** [comment]
@sger Did you want to merge that into master?

**Comment by sger** [comment]
@thanegill yes

**Comment by sger** [comment]
@thanegill looks perfect you can merge it with master if you want.

**Comment by thanegill** [comment]
@sger I'm fine with merging with master. Just didn't expect the immediacy. 😊

**Comment by thanegill** [comment]
@sger Can you trunk push the pod spec?
Since travis isn't setup to do it yet.

**Comment by sger** [comment]
@thanegill yes

**Pull request merged**
