### PR TITLE
fix ci build error

### PR DESCRIPTION
**Pull request by AYastrebov**

### CODE REVIEW

**Comment by freak4pc** [comment]
Please fix the CI on the branch of #25 (in a new PR)

**Comment by freak4pc** [comment]
That seems to not be related to the PR, I spoke too soon :( If you can keep trying to fix this I'd really appreciate it. If not, no worries, I'll try tackling later.

**Comment by AYastrebov** [comment]
@freak4pc ok, fixed ci build error, applied swift 4 and rxswift 4. All should be good now

**Comment by freak4pc** [comment]
Hey @AYastrebov - I prefer having the changes on the original PR, as he has already worked hard on that PR - and it is also detailed with commits. Let's take the changes to fix the test and put them on the original PR. That would be much more beneficial. 

Did you fix just `travis.yml` or any other changes needed ?

**Comment by AYastrebov** [comment]
@freak4pc done. Reverted swift 4 and rxswift 4. Fixed warnings, updated pods, tests are passing. All should be good now

**Pull request closed without merging**
