### PR TITLE
Revert "Update to RxSwift 4"

### PR DESCRIPTION
**Pull request by freak4pc**
Revert PR #25 
This PR was (accidentally?) merged while CI was broken, leaving master broken. 

Reverting to pre-PR state. When the PR is ready to be merged, we can merge back in.

### CODE REVIEW

**Comment by freak4pc** [comment]
OK this is super weird. the Push CI was clear, but the PR CI is red. very confused about this.

**Comment by bobgodwinx** [comment]
It was the reverted commit that passed on travis `56771f879763669de66139a44dec407bf2c8a15c`

**Comment by bobgodwinx** [comment]
this one here https://github.com/RxSwiftCommunity/RxMKMapView/commit/56771f879763669de66139a44dec407bf2c8a15c

**Comment by freak4pc** [comment]
Yeah @bobgodwinx but as you see the "Push" travis task is fine, but the PR one isn't. which is odd since they're supposed to be similar:

1aae85e5-4492-4584-8f4f-04ead98e1c3e

Why would the commit succeed but the PR not? its the same code.

**Comment by bobgodwinx** [comment]
Because it was a revert commit. That was passing evidently

**Comment by freak4pc** [comment]
But the PR is of that same commit, in time.

**Comment by bobgodwinx** [comment]
try running  #PR commit again on travis.

**Pull request merged**
