### PR TITLE
Update to RxSwift 3.0.0

### PR DESCRIPTION
**Pull request by victorg1991**
Finish the work started in https://github.com/RxSwiftCommunity/RxMKMapView/pull/15

### CODE REVIEW

**Comment by shams-ahmed** [comment]
anyone able to merge this branch to master?

**Comment by icanzilb** [comment]
This PR looks very solid! I wonder who is using the map view and can review & test quickly? @scotteg @bontoJR @fpillet ?

**Comment by scotteg** [comment]
Not currently using this but I'll check it out and let you know.

**Comment by scotteg** [comment]
I tested a handful of the operators. They all worked as advertised. Nicely done, thanks @victorg1991! 👏🏼 I'll merge this PR, and I'm going to use this in the new version of [LŌC](http://www.thelocapp.com) (which is in dire need of a complete rewrite since I last touched it in iOS 8, and it currently uses Parse 😫).

**Comment by shams-ahmed** [comment]
Can you push a updated version to cocoapods 👍🏻

**Comment by icanzilb** [comment]
@thanegill @sger can you guys push a new CocoaPod or give rights to someone else in the RxSwiftCommunity?

**Comment by sger** [comment]
@icanzilb of course whats your email?

**Comment by icanzilb** [comment]
@sger just sent you an email 👍

**Comment by sger** [comment]
@icanzilb cool you can push now

**Comment by scotteg** [comment]
@sger Do you want to update CP trunk, or else I have a few minutes now and can take care of it.

**Comment by sger** [comment]
@scotteg can you send me your email to add you also?

**Comment by scotteg** [comment]
Oh, lol, I thought I already was added. Maybe not. Just sent you an email.

**Comment by sger** [comment]
@scotteg cool you can push now

**Comment by scotteg** [comment]
Ok, so who's going to do it? Thumbs up if you want to, or else I'll do it in 5 min.

**Comment by scotteg** [comment]
@sger After dealing with CP issues, the podspec is still failing lint because `resource_bundles` doesn't match anything. The `Pod/Assets` directory is empty (except for a `.gitkeep`). Do you need to include it? When I comment that out in the podspec, it passes lint.

**Comment by scotteg** [comment]
Hi @sger, the latest release hasn't been pushed to CP trunk yet. I was waiting to hear back from you on my previous question. Let me know and I can take care of it. Thanks!

**Pull request merged**
