### PR TITLE
 Support rendering of the MKOverlay class

### PR DESCRIPTION
**Pull request by xiaohu557**
- Add the 'overlay' binder to the map

### CODE REVIEW

**Review by freak4pc — COMMENTED** [review]
Overall looks good - I dislike the fact we're breaking the public interface, though. 
I also don't really like the two separate data sources - can we unify them somehow ? 

@mkko care to give a second pair of eyes?

**Review by mkko — APPROVED** [review]
Looks great! Thank you for the contribution 🎉

**Comment by mkko** [comment]
It's true that the two data sources are identical, but from my point of view they have a bit different responsibilities. Combining them would seem a bit over engineering. Where do you @freak4pc see we'd be breaking public interface and how?

**Comment by freak4pc** [comment]
Oh, sorry it's just an internal class - all good. Let's do it!

**Comment by xiaohu557** [comment]
Thank you guys for merging this! 👍

**Pull request merged**
