### PR TITLE
Update to RxSwift 4

### PR DESCRIPTION
**Pull request by diogot**
Also Xcode 9 and Swift 4

### CODE REVIEW

**Comment by freak4pc** [comment]
@AYastrebov Why did you merge this if CI failed ?

**Comment by freak4pc** [comment]
@AYastrebov I've reverted the merged changes until CI is passing, please never merge stuff to master if the CI is broken. 

Open a new PR with this same branch and the fixed CI issues and we can merge that in

Thanks for the work @diogot !

**Comment by diogot** [comment]
Ok, I was debugging the reason of the CI fail but the Travis is too slow, and I forgot to continue. It's passing on my machine.
I'll keep investigating.

Thanks

**Comment by AYastrebov** [comment]
@freak4pc @diogot sorry for that merge. I've fixed ci in #26

**Comment by freak4pc** [comment]
@AYastrebov Thanks for your persistence !

@diogot Can you take @AYastrebov's changes from #26 into your branch and make a new PR? If everything looks good we can merge.

**Comment by diogot** [comment]
It looks like this is taking care in #28, let me know if you need help on something.

**Comment by freak4pc** [comment]
Thanks @diogot , #28 is actually entirely your code ! I just took your commits and overlaid them with some minor fixes and CI adjustments

**Pull request merged**
