### PR TITLE
Update to Swift 5.0

### PR DESCRIPTION
**Pull request by iwb-mohamed-louli**

### CODE REVIEW

**Comment by dfmarulanda** [comment]
@freak4pc this works?

**Comment by freak4pc** [comment]
CI is still failing ... it should be fixed before we can move forward with the review. @iwb-mohamed-louli @Dfmarulanda

**Comment by freak4pc** [comment]
Fixed in #45 and release in RxMKMapView 5.0.

**Comment by iwb-mohamed-louli** [comment]
> Fixed in #45 and release in RxMKMapView 5.0.

Sorry I forgot to respond to all your messages, "Yes" it was working and it still works in our production app, it strange that CI was failing, but anyway you fixed it now in #45 thank you so much, we will use your repo very soon.

**Pull request closed without merging**
