### PR TITLE
Annotation binding with updates

### PR DESCRIPTION
**Pull request by mkko**
Discussed in [#22](https://github.com/RxSwiftCommunity/RxMKMapView/issues/22), the current version of annotation binding does not update by removing the old values when the bound variable updates. Instead, everything is kept and adding new values to the bound variable will basically just add the previous values over again. This behaviour is different with other Rx bindings, such as the ones with UITableView where the table view component will react to the changes by also clearing removed values and thus reflecting the actual state of the observable on the UI.

In this PR the goal is to add this behaviour to the annotation binding. For the user the breaking changes would be the following:

* Binding a single annotation (as opposed to a sequence) to the map is not possible anymore. However, you can simple put the annotation to an array to make this work.
* Binding to the annotations will only keep the latest value on the map and the previous values will be removed from the map. This means that using a binding such as one from the tests: `Observable.from([a1, a2, a3]).bindTo(mapView.rx.annotations)` would only keep the last item on the list. However, for the previous reason this doesn't work anymore, as the bound value would have to be `[[a1], [a2], [a3]]` (or `[[a1, a2, a3]]`).

Besides handling the removal this PR enables customisation of the ui handling logic (look `RxMapViewReactiveDataSource` for a simple logic).

This PR is a work in progress due to:

* [x] The API change needs to be verified
* [x] Diff algorithm could be improved
* [x] More tests
* [x] Version bump for the library is required

### CODE REVIEW

**Comment by freak4pc** [comment]
Hey @mkko ! 
Super super sorry I didn't have time to look back into this. Any change you can rebase on master and I can review again ? I think this approach is better than the one we have today and is more Rx-y for sure. 

No pressure though! take your time

**Comment by mkko** [comment]
No worries, I've been using local branch and didn't really need this to be merged. But yeah, I'll gladly do it this evening. Happy to get this merged.

**Comment by mkko** [comment]
I rebased it now. I also enabled the use of Bundler to be able to run the specified version of cocoapods, if you don't mind. Could be another example, but this applies for the example only.

**Comment by freak4pc** [comment]
@mkko Thanks for getting this ready for review and for your patience! Gonna try this on our codebase later today or tomorrow and give some answers. :)

**Review by freak4pc — CHANGES_REQUESTED** [review]
Hey @mkko , Was able to toy around with this a bit. First of all i think this is really a great great addition and is the missing piece for this project ATM.

There are a couple of points here that I think might be needed to be taken care of before we can move on adding this to the main repo. 

1. We need a good example of how to use this on the Example ViewController. This means showing some annotations data source bound to the Map View and also "changing" the Data Source so its easily visible how it works "Reactively".
2. I wonder if we can replace Diff.swift with something like [Differentiator](https://github.com/RxSwiftCommunity/RxDataSources/blob/master/Differentiator.podspec) from RxDataSources and save having to maintain a riffing library. Perhaps thats a bit too much extra overhead for this use case but I'm not entirely sure 🤔 
3. Could you elaborate on what's the need for this protocol method and how is it used? https://github.com/RxSwiftCommunity/RxMKMapView/pull/24/files#diff-9d354053e7df28ff150400e0384fb18eR22
4. There has to be a good way to do some side-effects as the annotations are bound. First thing to come to mind is to zoom the map around the annotations. I'm sort of contemplating whether or not this should just be done in a `do` block, but am worried it might be a bit involved. Still thinking about this and would love your opinion. 
5. I'm not sure why but it seems you're not disposing things in your test - I think (even though its short lived) its better to put all tested observables in a Dispose Bag that's part of the test (or manually dispose if needed to hold for longer). 

Overall really great stuff ! 👏

**Comment by freak4pc** [comment]
PS no need (right now) to add the Gemfile as it was decided to push the Pods folder to speed up CI times, so it should be easy to just compile "out of the box"

**Comment by mkko** [comment]
Sorry, this got delayed due to other things. The next thing I'll do is the example for this. Here's to your questions:

2. I looked into the Differentiator, but decided to go for better performance, since we only need adds and removes and nothing else. I also think that the diff is of great importance and thus prefer to keep close control over it. If you don't mind, separating this could be done as a separate pull request.
3. This I simply imitated the style from [RxTableViewSectionedReloadDataSource.swift](https://github.com/RxSwiftCommunity/RxDataSources/blob/ae7d354dc25cc4e517cb72e00a068669aac97cfd/Sources/RxDataSources/RxTableViewSectionedReloadDataSource.swift). The data source is the customizable part that handles the integration with the UI (addition, removal). Would you improve this in some way?
4. That is a good question. I actually don't know any other way than the `do` block you mentioned. I don't think there's any clear way to support this without adding complexity. In the end the binding is one-way and source can be observed besides being bound. I might not be the best person to give an opinion in general on this topic, since I tend to drive towards pragmatism though. What do you mean by it being a bit involved? It's nice to have a full-feature API but for a library such as this, however, being able to compose your own logic is crucial. Also I would point out that the binding is working on annotations, and there is a dedicated callback for the views (`didAddAnnotationViews:`) which might be preferred in some scenarios. Since dealing with the UI, I think we only have unclean solutions.
5. Good catch. As you said, I was only considering them short lived and thus, didn't even think about it. I'll fix this.

For the example, I'm thinking of something that binds the current viewport to annotations from a local file. As a bonus, the annotations could be searched the results would be displayed on the map. What do you think?

No promises though on the bonus, as it took me so long to reply here at all 🙃.

**Comment by mkko** [comment]
I've updated the PR and rebased it on top of the latest master.

I added an example that combines two sources into the binding, enabling the filtering of the annotations. The included CSV containing cities is licensed under MIT, but I wasn't sure if or how to note that there.

@freak4pc, how would this work for you?

**Comment by freak4pc** [comment]
I'll need to find some time to review this, hopefully in the next few days, but if not it'll have to wait for the weekend 👍 Again, thank you very much for taking the time here. 

Regarding the CSV, can you show me where you got it from?

**Comment by mkko** [comment]
Thanks, and no worries. The CSV is available [here](https://simplemaps.com/data/world-cities).

**Comment by freak4pc** [comment]
@mkko Thanks. the website you linked to specifically says "No attribution required" so all good :)

**Comment by mkko** [comment]
Hi @freak4pc! It's been a while since there was activity here. Do you feel there's something still pending with this one?

**Comment by freak4pc** [comment]
You're absolutely correct. No good excuse here besides I've been insanely busy with other community (and non-community projects) and forgot. I'm currently in Manhattan for work so it would be hard for me to experiment with this approach but I'll write myself a reminder to try and do so this upcoming weekend.

Thanks again and sorry keeping you on hold for so long!

**Comment by freak4pc** [comment]
Just wanted to circle back and say I hope to look into this sooner. Have been super swamped but I really want to get this in for a next minor/major bump. If anyone else has some free time to give this some love, that’d be great. @RxSwiftCommunity/contributors

I’ll try to look myself later on.

**Comment by mkko** [comment]
Hi @freak4pc! Any chances we could merge this soon?

**Comment by freak4pc** [comment]
Really sorry about this again. Have been through a lot of work lately :) I hope to look at this this week, but I'm also flying to WWDC at the end of the week so can't make any promises. If anyone else wants to review this until I do that'd be great! @RxSwiftCommunity/contributors

**Comment by freak4pc** [comment]
@mkko Really really great job here! This works very well and I can't wait to add this to our actual live code base :) 

I made a few cleanups and adjustments to make usage more Rx-y and less imperative. Also cleaned up the searched vs. region observable as a single one.

Let me know what you think!

P.S Version bump will be done in master after this is merged.

**Review by freak4pc — APPROVED** [review]

**Comment by freak4pc** [comment]
@mkko Found one more minor issue fixed in https://github.com/RxSwiftCommunity/RxMKMapView/pull/24/commits/7e58c8ff9447af0f99122e6575c928e762e35954

You didn't add any way to install a Forward Delegate. Which means, if a user manually sets his delegate by code, it would collide with the Delegate Proxy used by Rx and the example would break. 

In the previous example, it was only an accident the code worked (merely because the Storyboard was used to set the delegate)

Let me know if you have any further questions

**Comment by mkko** [comment]
Thank you for all the work and pushing this forward!

I actually didn't even think there would be a way to handle delegates like this, thanks for letting me know! Many things Rx are still unknown to me. Also cleaning up the example was great idea, I tend to neglect that. Thanks for that as well!

No further questions. Please let me know if there's something I can help you with.

**Comment by freak4pc** [comment]
Thanks for all your work and patience on this PR, and welcome to RxSwiftCommunity @mkko ! 🎉 🎉 🎉

**Comment by mkko** [comment]
Thank you as well, picked up cool Rx-y things while working with you.

**Pull request merged**
