### PR TITLE
Swift 4.2 support

### PR DESCRIPTION
**Pull request by diogot**
Based on #37, but without the icon changes.

- Uses the stable CocoaPods (1.5.3)
- Uses RxSwift 4.3.1
- Saves build logs and tests results to be reviewed in CircleCI builds
- Some clean up in CircleCI config file
- Change `.gitignore` to ignore `Carthage` directory just on the root, one of the pods have a directory with the same name

### CODE REVIEW

**Comment by diogot** [comment]
I don't have access to rebuild without cache in CircleCI, can anyone do it for me?
https://circleci.com/gh/RxSwiftCommunity/RxMKMapView/55#tests/containers/0

Thanks!

**Comment by freak4pc** [comment]
@diogot Done

**Comment by diogot** [comment]
Thanks!

**Comment by diogot** [comment]
I guess it's done.
We should consider to don't commit the `Pods` directory, to make sure the PRs use the same CocoaPods version.

**Comment by freak4pc** [comment]
@diogot There are fors and against comitting the Podfile - I'm personally for (you can compile as you immediately clone, for example).

**Comment by freak4pc** [comment]
This overall looks good to me by the way. Any chance someone else can take an eye? @mkko perhaps if you have a few minutes ?

**Comment by diogot** [comment]
I agree that is a lot of debates around it, with fors and againsts.
I think that in this case might be useful, given that we want the library to work with an external dependency on CocoaPods. So if the Pods are not check-in, the CI will test if this is working.
But no big deal.

**Review by mkko — APPROVED** [review]

**Comment by mkko** [comment]
Looks and builds good to me.

**Comment by mkko** [comment]
I'm also for keeping the Pods checked in. I think the only downside is that it adds a lot of noise for PR diffs. It's still better to have a buildable system though.

**Comment by mkko** [comment]
Oh, and thank you @diogot for this PR!

**Pull request merged**
