### PR TITLE
Upgrade to RxSwift 6.0

### LINKED ISSUE #52: Upgrade to RxSwift 6.0

### PR DESCRIPTION
**Pull request by bigMOTOR**

### CODE REVIEW

**Comment by bigMOTOR** [comment]
Hi @sjrmanning could you please take a look at my PR?

**Comment by bigMOTOR** [comment]
@freak4pc Hi! Could you take a look at this PR please?

**Comment by freak4pc** [comment]
Hey @minuscorp  - you [noted you're taking care of this project](https://github.com/RxSwiftCommunity/contributors/issues/67), any chance you can take a look here?

**Comment by minuscorp** [comment]
Yeah, I was sick all the week and hadn't time for it, I'll review ASAP!

**Comment by freak4pc** [comment]
Awesome, no rush. Get well soon :)

**Comment by minuscorp** [comment]
I'll check if no code changes are needed though, just a bump.

**Comment by bigMOTOR** [comment]
@minuscorp Hi! Sorry for bothering. What is happening with my PR? 🙂

**Comment by minuscorp** [comment]
It needs some changes in the Example Podfile.lock, but I'm in isolation and cannot have a computer so from the iPad I cannot make a pod install and pod update of the Example Podfile and push it and make the last check to pass successfully, could you do that for me? 😅 Sorry for the time it has passed

**Comment by bigMOTOR** [comment]
@minuscorp Thanks for your response! I did Example's Pod update, looks like all checks passed.

**Pull request merged**
